spring:
  application:
    name: jungle
  profiles:
    default: dev
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.config.server-addr}
server:
  port: 9000
  shutdown: graceful

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: true
      logic-not-delete-value: false
nacos:
  config:
    server-addr: localhost:8848

grpc:
  server:
    port: 0
    enable-keep-alive: true
  client:
    alps:
      negotiation-type: PLAINTEXT
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jungle
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jungle
    password: jungle
  config:
    activate:
      on-profile: dev
jungle:
  mode: standalone
  cluster:
    keep-connected: true
    ip-prefer: 192.168

