spring:
  application:
    name: jungle
  profiles:
    default: dev
  lifecycle:
    timeout-per-shutdown-phase: 30s
server:
  port: 0
  shutdown: graceful

---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jungle
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jungle
    password: jungle
  h2:
    console:
      enabled: true
      path: /h2-console
  config:
    activate:
      on-profile: dev
jungle:
  mode: standalone
  cluster:
    keep-connected: true
    ip-prefer: 192.168
