spring:
  application:
    name: jungle
  profiles:
    default: dev
  lifecycle:
    timeout-per-shutdown-phase: 30s
server:
  port: 0
  shutdown: graceful

---
spring:
  datasource:
    url: jdbc:h2:mem:jungle_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: jungle
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  config:
    activate:
      on-profile: dev
jungle:
  mode: cluster
  cluster:
    keep-connected: true
    ip-prefer: 192.168
