spring:
  application:
    name: jungle
  profiles:
    default: dev

---
spring:
  datasource:
    url: jdbc:h2:mem:jungle_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: jungle
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  config:
    activate:
      on-profile: dev
